### ISSUE TITLE
ctx.strokeStyle = "red" produces no error or code.

### ISSUE THREAD

**Issue by treeform** [define-private-public/HTML5-Canvas-Nim#1]
It is very odd, `ctx.strokeStyle = "red"` produces no error or js code. It should either:
* Fail and say strings are not supported.
* Produce the js code.

Using `ctx.strokeStyle = cstring("red")` or `ctx.strokeStyle = rgb(255,0,0)` works fine.

**Comment by treeform** [comment]
Defining this proc makes it work. I think some thing with auto `cstring` to `string` conversion is odd.

```
proc `strokeStyle=`*(
  ctx: CanvasRenderingContext2D;
  color: string
) {.inline.} =
  {.emit: [ctx, ".strokeStyle=", cstring(color), ";"].}
```

**Comment by define-private-public** [comment]
What version of Nim are you using?  I'm on 0.17.2, and it working just fine for me.  Take a look at the test entitled `rectTest()` in `test.nim`.  I'm using named color string there and it works.

**Comment by treeform** [comment]
This was an issue on my end. Now its fixed. Thank you!
